name: ci-golang-workflow

on: 
  pull_request:
    branches:
      - develop 

jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.19', '1.18', '1.17', '1.15', '1.14', '1.13', '1.12']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test
      - run: go run math.go

      # # Docker and Push
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ DOCKERHUB_USERNAME.DOCKERHUB_USERNAME }}
      #     password: ${{ DOCKERHUB_USERNAME.DOCKERHUB_TOKEN }}

      # - name: Build and push Docker images
      # #   id: docker_build
      #   uses: docker/build-push-action@v6
      #   with:
      #     push: true
      #     tags: lucaspintof5/fc2.0-ci-go:latest

    